### ISSUE TITLE
zooming image displays a scaled-up version of the low res image behind the full size version of the actual image when clicked

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/learncms#15] opened 2015-08-24 15:02 UTC
when clicked, the zooming image displays the correct, full-size image. however, a scaled-up version of the smaller image used as an icon is also visible if you scroll down. found in safari but this problem persists in firefox and chrome
![screen shot 2015-08-24 at 9 57 05 am](https://cloud.githubusercontent.com/assets/6078575/9443504/05602a66-4a47-11e5-9625-4902009d7d02.png)

**Comment by JoeGermuska** [comment] 2015-09-03 20:13
this is a duplicate of #31 but that one has more explanation

**Closed as completed by JoeGermuska** 2015-09-03 20:13 UTC
