### ISSUE TITLE
Can't insert links within glossary terms

### ISSUE THREAD

**Issue by AditiBhandari** [NUKnightLab/learncms#76] opened 2015-10-08 15:55 UTC
E.g. in the HTML lesson, the W3C glossary tag is supposed to include a hyperlink to their website but the linking doesn't work because markup isn't supported there I guess
![screen shot 2015-10-08 at 10 55 06 am](https://cloud.githubusercontent.com/assets/9308945/10371918/1446b5ea-6dab-11e5-8020-7899f2cb7937.png)

**Comment by JoeGermuska** [comment] 2015-10-08 15:56
duplicate of #45

**Closed as completed by JoeGermuska** 2015-10-08 15:56 UTC
