### ISSUE TITLE
Enable writing markup in glossary terms

### ISSUE THREAD

**Issue by AditiBhandari** [NUKnightLab/learncms#79] opened 2015-10-12 19:28 UTC
![screen shot 2015-10-12 at 2 28 14 pm](https://cloud.githubusercontent.com/assets/9308945/10436671/816b321e-70ed-11e5-94dc-a571b32edd06.png)
It's easier to explain certain terms using markup

**Comment by JoeGermuska** [comment] 2015-10-12 21:17
duplicate of #76 and #45 :)

**Closed as completed by JoeGermuska** 2015-10-12 21:17 UTC
